# -*- coding: utf-8 -*-
"""ingredientsList.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OGAPjQuoS-wRiP8tUgVZW6lHn17SyqZH
"""

from google.colab import files
import io
import numpy as np
import pandas as pd

df = pd.read_excel(r'vkusvillnew.xlsx', )

df = df.drop(columns=["Название", "Родительская категория", "Категория", "Цена", "Белки", "Жиры", "Углеводы", "Энергетическая ценность", "Вес/объем", "Ссылки на изображения", "Ссылка на товар"])

df = df.drop(columns="Unnamed: 0")

df

new_df = pd.DataFrame(columns=['Ингредиенты'])

for index, row in df.iterrows():
    if pd.isna(row['Состав']):
        continue
    ingredients = row['Состав'].split(',')
    for ingredient in ingredients:
        new_row = pd.DataFrame({'Ингредиенты': [ingredient.strip()]})
        new_df = pd.concat([new_df, new_row], ignore_index=True)

new_df = new_df.drop_duplicates()

new_df

new_df.to_csv('ingredientsList.csv', index=False)

