# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yYQxakSnRBfacWq3pNC6GtrjnrmkEp7h
"""

from google.colab import files
import io
import pandas as pd

df = pd.read_excel(r'/content/2019-10-30_vkusvill.xlsx', )

df = df.drop(columns=["Код", "Единицы измерения", "Описание", "Информация", "Дата обновления", "Регион"])

df.head(5)

df['Название'] = df['Название'].str.lower()

df.to_excel("vkusvillnew.xlsx")

df = df.drop(columns=["Родительская категория", "Категория", "Цена", "Белки", "Жиры", "Углеводы", "Энергетическая ценность", "Состав", "Вес/объем", "Ссылки на изображения", "Ссылка на товар"])

df

df['Название'] = df['Название'].apply(lambda x: x.split()[0])

df = df.drop_duplicates()

df

df.to_excel("productsList.xlsx")